package com.work.mautonlaundry.services;

import com.work.mautonlaundry.data.model.enums.ReferralPaymentFrequency;
import com.work.mautonlaundry.data.repository.ReferralPaymentRuleRepository;
import com.work.mautonlaundry.data.repository.ReferralPayoutRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.temporal.IsoFields;
import java.time.temporal.WeekFields;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Daily job (06:00 Africa/Lagos) that generates PENDING payout records for
 * referrers whose payment-frequency schedule falls due today. It never
 * auto-approves or auto-pays — an admin (Tolulope) reviews, approves and marks
 * paid from the portal.
 *
 * <p>{@code ON_DEMAND} and {@code PER_MILESTONE} are intentionally not handled
 * here: ON_DEMAND is admin-triggered, and PER_MILESTONE payouts are generated by
 * the admin when the milestone notification fires (the schedule has no fixed
 * calendar cadence).
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class ReferralPayoutScheduler {

    private final ReferralPaymentRuleRepository ruleRepository;
    private final ReferralPayoutRepository payoutRepository;
    private final ReferralService referralService;

    @Scheduled(cron = "${app.referral.payout-cron:0 0 6 * * *}", zone = "Africa/Lagos")
    public void generateScheduledPayouts() {
        LocalDate today = LocalDate.now(java.time.ZoneId.of("Africa/Lagos"));
        Map<ReferralPaymentFrequency, Period> due = duePeriods(today);
        if (due.isEmpty()) {
            return;
        }
        log.info("Referral payout job running for {} — due frequencies: {}", today, due.keySet());

        for (Map.Entry<ReferralPaymentFrequency, Period> entry : due.entrySet()) {
            ReferralPaymentFrequency frequency = entry.getKey();
            Period period = entry.getValue();
            List<String> referrerIds = ruleRepository.findReferrerIdsWithActiveFrequency(frequency);
            for (String referrerId : referrerIds) {
                try {
                    if (payoutRepository.existsByReferrerIdAndPeriodFromAndPeriodTo(
                            referrerId, period.from(), period.to())) {
                        continue; // already generated for this period
                    }
                    referralService.generatePayoutRecord(referrerId, period.from(), period.to(), "SCHEDULER");
                } catch (Exception ex) {
                    log.error("Failed to generate {} payout for referrer {}: {}",
                            frequency, referrerId, ex.getMessage(), ex);
                }
            }
        }
    }

    /** Which payment frequencies are due on {@code today}, each with its covered period. */
    private Map<ReferralPaymentFrequency, Period> duePeriods(LocalDate today) {
        Map<ReferralPaymentFrequency, Period> due = new LinkedHashMap<>();

        boolean isMonday = today.getDayOfWeek() == DayOfWeek.MONDAY;
        if (isMonday) {
            // Every Monday: previous 7 days (Mon..Sun).
            due.put(ReferralPaymentFrequency.WEEKLY, new Period(today.minusDays(7), today.minusDays(1)));

            // Every other Monday (even ISO week): previous 14 days.
            int week = today.get(WeekFields.of(Locale.UK).weekOfWeekBasedYear());
            if (week % 2 == 0) {
                due.put(ReferralPaymentFrequency.FORTNIGHTLY, new Period(today.minusDays(14), today.minusDays(1)));
            }
        }

        if (today.getDayOfMonth() == 1) {
            // 1st of the month: the whole previous calendar month.
            LocalDate prevMonthEnd = today.minusDays(1);
            LocalDate prevMonthStart = prevMonthEnd.withDayOfMonth(1);
            due.put(ReferralPaymentFrequency.MONTHLY, new Period(prevMonthStart, prevMonthEnd));

            // 1st of a quarter: the previous calendar quarter.
            int month = today.getMonthValue();
            if (month == 1 || month == 4 || month == 7 || month == 10) {
                LocalDate quarterStart = today.minusMonths(3).with(IsoFields.DAY_OF_QUARTER, 1L);
                due.put(ReferralPaymentFrequency.QUARTERLY, new Period(quarterStart, today.minusDays(1)));
            }
        }
        return due;
    }

    private record Period(LocalDate from, LocalDate to) {
    }
}
